- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- lib/main.dart
- lib/src/constants.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/select_theme_dialog.dart
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile
- pubspec.lock
- pubspec.yaml
- test/widget_test.dart
- Close #2
- 「ライト」・「ダーク」・「システムのデフォルト」のテーマ切り替え
- ローカルにテーマを保存
- popupmenu
- 「テーマの選択」用のdialog
```
[x] Yes
[ ] No
```
- コメントとしていくつか `TODO` がある
- ラジオボタンのところは、とりあえずは「OK」を押すまでテーマは変わらないようになっている（Google 製アプリもそうなので、許してください）
> feat: テーマ切り替えを実装

- lib/main.dart
- lib/src/screens/home.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/select_theme_dialog.dart
- pubspec.lock
- pubspec.yaml
- Close #4
- locales を日本語に設定
- 不要なカンマを削除
```
[x] Yes
[ ] No
```
-
> feat: 日本語へのローカライズ設定

- lib/main.dart
- lib/src/app.dart
- lib/src/constants.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/select_theme_dialog.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- test/widget_test.dart
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Close #7
- `dynamic_color` のインストール・設定
- コード分割・変数名修正等のリファクタリング
```
[x] Yes
[ ] No
```
-
> feat: dynamic color に対応

- lib/src/widgets/default_popup_menu.dart
- Close #10
```
[x] Yes
[ ] No
```
-
> feat: PopupMenu の位置を Button の下に

- lib/src/app.dart
- lib/src/screens/history.dart
- Close #
```
[x] Yes
[ ] No
```
-
> feat: 履歴ページを作成

- android/app/build.gradle
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner/Info.plist
- lib/src/screens/home.dart
- lib/src/widgets/scan_code.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- web/index.html
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Close #12
```
[x] Yes
[ ] No
```
> feat: コード読み取り機能の追加

- lib/src/screens/history.dart
- lib/src/utils.dart
- Close #
```
[x] Yes
[ ] No
```
-
> feat: 履歴の追加機能

- lib/src/screens/history.dart
- lib/src/utils.dart
- lib/src/widgets/scan_code.dart
- Close #
```
[x] Yes
[ ] No
```
-
> feat: 読み取った文字列を保存

- android/app/src/main/AndroidManifest.xml
- lib/src/screens/history.dart
- lib/src/utils.dart
- lib/src/widgets/scan_code.dart
- Close #
```
[x] Yes
[ ] No
```
-
> feat: コピー・ブラウザで開く・共有

- lib/src/screens/home.dart
- lib/src/widgets/qr_i_o.dart
- lib/src/widgets/scan_code.dart
- Close #19
```
[x] Yes
[ ] No
```
-
> feat: 画面遷移

- lib/src/screens/history.dart
- lib/src/screens/home.dart
- Close #30
```
[x] Yes
[ ] No
```
-
> feat: 履歴の表示

- lib/src/widgets/scan_code.dart
- Close #33
```
[x] Yes
[ ] No
```
-
> feat: 不要な機能の削除

- lib/src/constants.dart
- lib/src/qr_image_config.dart
- lib/src/screens/editor.dart
- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/select_qr_background_color_dialog.dart
- lib/src/widgets/select_qr_data_module_shape_dialog.dart
- lib/src/widgets/select_qr_error_correct_level_dialog.dart
- lib/src/widgets/select_qr_eye_shape_dialog.dart
- lib/src/widgets/select_qr_foreground_color_dialog.dart
- lib/src/widgets/select_theme_dialog.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- #18
```
[x] Yes
[ ] No
```
-
> feat: QRコード作成画面の実装

- lib/src/screens/editor.dart
- lib/src/widgets/qr_i_o.dart
- Close #39
```
[x] Yes
[ ] No
```
-
> feat: 画面遷移の追加

- lib/src/screens/history.dart
- lib/src/utils.dart
- Close #41
```
[x] Yes
[ ] No
```
-
> feat: 履歴削除

- lib/src/screens/history.dart
- Close #44
```
[x] Yes
[ ] No
```
-
> chore: disableボタンの色変更

- lib/src/screens/history.dart
- Close #46
```
[x] Yes
[ ] No
```
-
> chore: blur調整

- lib/src/app.dart
- lib/src/constants.dart
- lib/src/screens/history.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/qr_i_o.dart
- Close #48
```
[x] Yes
[ ] No
```
-
> feat: 履歴の表示拡大

- lib/src/screens/home.dart
- Close #45
```
[x] Yes
[ ] No
```
-
> feat: キーボード対策

- lib/src/widgets/scan_code.dart
- Close #43
```
[x] Yes
[ ] No
```
-
> feat: フラッシュアイコン設定

- lib/src/app.dart
- lib/src/screens/editor.dart
- lib/src/screens/history.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/select_qr_background_color_dialog.dart
- lib/src/widgets/select_qr_data_module_shape_dialog.dart
- lib/src/widgets/select_qr_error_correct_level_dialog.dart
- lib/src/widgets/select_qr_eye_shape_dialog.dart
- lib/src/widgets/select_qr_foreground_color_dialog.dart
- Close #23
```
[x] Yes
[ ] No
```
-
> feat: 履歴画面の編集ボタンのイベントを実装

- lib/src/app.dart
- lib/src/widgets/config_items.dart
- Close #9
```
[x] Yes
[ ] No
```
-
> fix: 背景色のバグ修正

- lib/src/screens/history.dart
- lib/src/widgets/config_items.dart
- Close #57
```
[x] Yes
[ ] No
```
-
> fix: TextField に文字列を入力できないバグを解消

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- Close #15
```
[x] Yes
[ ] No
```
-
> chore: 不具合報告の動作環境を Flutter 用に修正

- lib/src/app.dart
- lib/src/utils.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/scan_code.dart
- pubspec.lock
- pubspec.yaml
- Close #68
```
[x] Yes
[ ] No
```
-
> feat: 共有機能追加

- lib/src/widgets/qr_code_preview.dart
- Close #72
```
[x] Yes
[ ] No
```
-
> fix: QRコード画像共有のバグ修正

- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/default_popup_menu.dart
- Close #34
```
[x] Yes
[ ] No
```
-
> feat: ダイアログを開くための関数をカリー化

- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/icon_box.dart
- Close #20
```
[x] Yes
[ ] No
```
-
> feat: TextField のアイコンを PrefixIcon から Row でラップする実装に修正

- lib/src/constants.dart
- lib/src/widgets/history.dart
- Close #78
```
[x] Yes
[ ] No
```
-
> feat: リンクを識別しやすく

- lib/src/screens/home.dart
- lib/src/widgets/custom_bottom_sheet.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qr_code_preview.dart
- Close #80
```
[x] Yes
[ ] No
```
-
> CustomBottomSheetの追加

- lib/src/constants.dart
- lib/src/enums/default_popup_menu_items_type.dart
- lib/src/qr_image_config.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/custom_qr_image.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/select_option.dart
- lib/src/widgets/select_qr_config_dialog.dart
- lib/src/widgets/select_theme_dialog.dart
- Close #71
```
[x] Yes
[ ] No
```
-
> feat: 背景色の選択を廃止し、前景背景の入れ替えにする

- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/history.dart
> feat: popup menuの背景色変更

- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- Close #85
```
[x] Yes
[ ] No
```
-
> feat: 作成画面の設定項目にタイトルを追加など

- lib/src/constants.dart
- lib/src/enums/default_popup_menu_items_type.dart
- lib/src/widgets/default_popup_menu.dart
- Close #62
```
[x] Yes
[ ] No
```
-
> chore: アイコン追加

- lib/src/widgets/config_items.dart
- Close #89
```
[x] Yes
[ ] No
```
-
> feat: 色の反転のアイコンを変える

- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- Close #91
```
[x] Yes
[ ] No
```
-
> feat: QRコード作成画面内の修正

- lib/src/constants.dart
- Close #93
```
[x] Yes
[ ] No
```
-
> feat: SeedColor を変更

- lib/src/constants.dart
- Close #95
```
[x] Yes
[ ] No
```
-
> feat: 誤り訂正部分のアイコン修正

- .gitignore
- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/app/web/qrio/MainActivity.kt
- android/app/src/profile/AndroidManifest.xml
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- linux/CMakeLists.txt
- linux/my_application.cc
- macos/Runner/Configs/AppInfo.xcconfig
- web/index.html
- web/manifest.json
- windows/runner/Runner.rc
- Close #
リリース用変更
```
[x] Yes
[ ] No
```
-
> chore: リリース用変更

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- pubspec.yaml
- Close #
```
[x] Yes
[ ] No
```
-
> chore: アクセス許可の表現を日本語に修正

- lib/src/widgets/bottom_snack_bar.dart
- Close #100
```
[x] Yes
[ ] No
```
-
> fix: `BottomSnackBar`の引数に`key`を追加

- lib/src/screens/editor.dart
- Close #103
```
[x] Yes
[ ] No
```
-
> feat: Unfocus をウィジェットに切り出す

- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- Close #107
```
[x] Yes
[ ] No
```
-
> fix: gradle等の設定変更

- lib/src/screens/share_app.dart
- lib/src/widgets/default_popup_menu.dart
- pubspec.lock
- pubspec.yaml
- Close #102
```
[x] Yes
[ ] No
```
-
> feat: 共有機能を追加

- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- Close #108
```
[x] Yes
[ ] No
```
-
> feat: Switchのデザイン変更

- lib/src/widgets/config_item.dart
- lib/src/widgets/select_qr_config_dialog.dart
- Close #114
```
[x] Yes
[ ] No
```
-
> feat: QRコードの色を表示

- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/icon_box.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- Close #112
```
[x] Yes
[ ] No
```
-
> feat: 軽微なデザイン修正

- lib/src/widgets/scan_code.dart
- pubspec.lock
- pubspec.yaml
- Close #113
```
[x] Yes
[ ] No
```
-
> feat: ギャラリーの写真をスキャン可能に

- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/src/screens/share_app.dart
- lib/src/widgets/qrio.dart
- pubspec.lock
- pubspec.yaml
- Close #117
```
[x] Yes
[ ] No
```
-
> feat: 共有で履歴に追加

- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- lib/src/widgets/select_qr_config_dialog.dart
- Close #120
```
[x] Yes
[ ] No
```
-
> feat: デザインの改善・修正

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- ios/Runner/Runner.entitlements
- ios/share/Base.lproj/MainInterface.storyboard
- ios/share/Info.plist
- ios/share/ShareViewController.swift
- ios/share/share.entitlements
- lib/src/widgets/qrio.dart
- Close #122
```
[x] Yes
[ ] No
```
-
> feat: 共有による履歴追加をiOSにも対応させる

- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/icon_box.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- Close #125
```
[x] Yes
[ ] No
```
-
> fix: padding等のデザイン修正

- android/app/src/main/AndroidManifest.xml
- lib/src/utils.dart
- lib/src/widgets/scan_code.dart
- pubspec.lock
- pubspec.yaml
- Close #128
```
[x] Yes
[ ] No
```
-
> feat: バイブレーション機能追加

- lib/src/constants.dart
- lib/src/widgets/history.dart
- Close #127
```
[x] Yes
[ ] No
```
-
> feat: DraggableScrollableSheetのデザイン変更

- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/scan_code.dart
- Close #131
```
[x] Yes
[ ] No
```
-
> feat: DraggableScrollableSheetの高さ変更

- lib/src/utils.dart
- lib/src/widgets/scan_code.dart
- Close #133
```
[x] Yes
[ ] No
```
-
> feat: 同時読み取り機能追加

- lib/src/constants.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/history.dart
- lib/src/widgets/select_qr_config_dialog.dart
- lib/src/widgets/select_theme_dialog.dart
- Close #42
```
[x] Yes
[ ] No
```
-
> feat: Dialogデザインの変更

- lib/src/widgets/qrio.dart
- Close #136
```
[x] Yes
[ ] No
```
-
> feat: 画像共有による履歴追加

- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/slider_qr_config_sheet.dart
- Close #137
```
[x] Yes
[ ] No
```
-
> feat: Slider、BottomSheetによる編集UIの作成

- lib/src/widgets/scan_code.dart
- Close #141
```
[x] Yes
[ ] No
```
-
> fix: Expandedにより発生するエラーの対処

- pubspec.yaml
- Close #97
```
[x] Yes
[ ] No
```
-
> chore: バージョン情報を更新

- ios/Runner/Info.plist
- Close #144
```
[x] Yes
[ ] No
```
-
> fix: 権限追加等

- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- ios/Runner/Runner.entitlements
- pubspec.yaml
- Close #
```
[x] Yes
[ ] No
```
-
> chore: バージョンを修正

- lib/src/widgets/history.dart
- Close #148
```
[x] Yes
[ ] No
```
-
> fix: パフォーマンスの改善

- lib/src/widgets/scan_code.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- Close #105
```
[x] Yes
[ ] No
```
-
> feat: QRコード読み取りに使用するライブラリを変更

- lib/src/widgets/scan_code.dart
- Close #153
```
[x] Yes
[ ] No
```
-
> feat: スキャン画面のデザイン変更

- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- Close #156
```
[x] Yes
[ ] No
```
-
> feat: DraggableScrollableSheetのUI変更

- lib/src/utils.dart
- lib/src/widgets/history_menu_sheet.dart
- pubspec.lock
- pubspec.yaml
- Close #155
```
[x] Yes
[ ] No
```
- ローカルへの保存形式をJSONにしたら、このPRの変更部分を要修正
> feat: CSVエクスポートを実装

- lib/src/constants.dart
- lib/src/utils.dart
- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- #154
```
[x] Yes
[ ] No
```
-
> feat: データの保存フォーマット変更

- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/widgets/history.dart
- Close #165
```
[x] Yes
[ ] No
```
-
> fix: 履歴スクロールの修正

- lib/src/widgets/history.dart
- Close #169
```
[x] Yes
[ ] No
```
-
> feat: 履歴bottomSheetを閉じる

- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- lib/src/widgets/select_theme_dialog.dart
- Close #173
```
[x] Yes
[ ] No
```
-
> fix: 問題を解決

- lib/src/utils.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- Close #157
```
[x] Yes
[ ] No
```
-
> feat: 個別削除機能

- lib/src/widgets/history.dart
- Close #179
```
[x] Yes
[ ] No
```
-
> feat: スターによる表示順の変更

- lib/src/constants.dart
- lib/src/utils.dart
- lib/src/widgets/history.dart
- Close #182
```
[x] Yes
[ ] No
```
-
> feat: 新規履歴の強調表示

- lib/src/screens/share_app.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qr_code_preview.dart
- Close #185
```
[x] Yes
[ ] No
```
-
> feat: スナックバーの削除処理追加

- lib/src/utils.dart
- lib/src/widgets/history.dart
- Close #187
- Close #190
```
[x] Yes
[ ] No
```
-
> fix: 不要な処理削除と処理変更

- .github/workflows/test.yml
- analysis_options.yaml
- Close #
- `analysis_options.yaml` にlintルールを追加
- CIで `flutter analyze` コマンドを実行するように
```
[x] Yes
[ ] No
```
-
> chore: set up lints

- lib/src/app.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/qrio.dart
- Close #194
```
[x] Yes
[ ] No
```
-
> feat:AppBarの自動変更

- lib/src/widgets/default_popup_menu.dart
- Close #202
```
[x] Yes
[ ] No
```
-
> feat: PopupMenuのカスタマイズ

- lib/main.dart
- lib/src/utils.dart
- lib/src/widgets/select_theme_dialog.dart
- Close #195
```
[x] Yes
[ ] No
```
-
> refactor: Stringとenumの変換

- lib/src/constants.dart
- Close #199
```
[x] Yes
[ ] No
```
-
> feat: バッジの表示時間を15秒に変更

- lib/src/app.dart
- Close #209
```
[x] Yes
[ ] No
```
-
> fix: ColorScheme を dynamic color に合わせる

- lib/main.dart
- lib/src/app.dart
- lib/src/constants.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/screens/share_app.dart
- lib/src/utils.dart
- lib/src/widgets/config_item.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/custom_qr_image.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- lib/src/widgets/qr_code_preview.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- lib/src/widgets/select_qr_config_dialog.dart
- lib/src/widgets/select_theme_dialog.dart
- lib/src/widgets/slider_qr_config_sheet.dart
- test/widget_test.dart
- Close #211
```
[x] Yes
[ ] No
```
-
> refactor: lintエラー箇所のリファクタリング

- android/build.gradle
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/src/app.dart
- lib/src/widgets/custom_qr_image.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qrio.dart
- macos/Podfile
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- pubspec.lock
- pubspec.yaml
- Close #213
```
[x] Yes
[ ] No
```
-
> fix: テーマを修正

- README.md
- Close #217
- `notchcoder` を `chnotchy` に変更
```
[x] Yes
[ ] No
```
-
> docs: ユーザー名の変更

- lib/src/app.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/history.dart
- lib/src/widgets/history_menu_sheet.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Close #83
- `InkWell` のリップルエフェクトを表示
```
[x] Yes
[ ] No
```
-
> fix: ripple effect

- lib/src/screens/editor.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- Close #221
```
[x] Yes
[ ] No
```
-
> feat: レイアウトの変更

- analysis_options.yaml
- android/app/build.gradle
- build.yaml
- lib/main.dart
- lib/src/app.dart
- lib/src/models/history_model.dart
- lib/src/models/history_model.freezed.dart
- lib/src/models/history_model.g.dart
- lib/src/qr_image_config.dart
- lib/src/qrio_state.dart
- lib/src/screens/editor.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/config_items.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/history.dart
- lib/src/widgets/qrio.dart
- lib/src/widgets/scan_code.dart
- lib/src/widgets/slider_qr_config_sheet.dart
- lib/src/widgets/unfocus.dart
- pubspec.lock
- pubspec.yaml
- test/widget_test.dart
- Close #146
- Close #200
- Close #66
- バージョン番号変更
- タブ切り替えのデザイン変更
- 機能追加
- リファクタリング
```
[x] Yes
[ ] No
```
-
> feat: UI/UX向上のための変更

- lib/src/qrio_state.dart
- lib/src/screens/home.dart
- lib/src/utils.dart
- lib/src/widgets/data_bottom_sheet.dart
- lib/src/widgets/default_popup_menu.dart
- lib/src/widgets/qrio.dart
- Close #201
```
[x] Yes
[ ] No
```
-
> feat: `TabBarView` を `PageView` に変更

- lib/src/widgets/history.dart
- Close #225
```
[x] Yes
[ ] No
```
-
> feat: アニメーション追加

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
> chore: release 1.1.1+8 for ios
